project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - Bisaccia_CV_2025-09-16.pdf

profile:
  default: english
  group: 
    - [english, italian]

website:
  title: "G. Bisaccia, MD-PhD"
  
  navbar:
    logo: images/profile.jpg
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: research.qmd
        text: Research & Tools
      - href: blog.qmd
        text: Blog
    right:
      - icon: file-earmark-text
        text: CV
        href: https://cv.bisacciamd.com
      - href: consulting.qmd
        text: Consulting
      - href: contact.qmd
        text: Contact
        
  #page-footer: "Developed with Quarto by Giandomenico Bisaccia — © 2024-2025" 
  reader-mode: false

format:
  html:
    theme: 
      light: [flatly, styles.css]
    css: styles.css
    toc: true
    toc-location: left
    include-after-body: _footer.html

csl: jacc-cvi.csl
execute: 
  freeze: true