---
title: "List of publications"
---

```{r}
#| echo: false
#| error: false
#| warning: false
#| output: false
library(bib2df)
pubs <- length(bib2df("cv.bib")$BIBTEXKEY)
```

I have authored or co-authored `r pubs` scientific publications. As first author, I performed any literature review or statistical analyses (where applicable), prepared the manuscript with feedback from all co-authors, and created visual illustrations and figures. Where a co-author, I participated in any literature review or statistical analyses, revised and approved the manuscript, and/or contributed to figures and/or  illustrations.

# Original research

## Cardiovascular imaging

**Atrial electro-functional predictors of incident atrial fibrillation in cardiac amyloidosis** (2024). G. Sinigiani, L. De Michieli, A. Porcari, C. Zocchi, A. Sorella, C. Mazzoni, G. Bisaccia, A. De Luca, G. Di Bella, D. Gregori, F. Perfetto, M. Merlo, G. Sinagra, S. Iliceto, M. Perazzolo Marra, D. Corrado, F. Ricci, F. Cappelli and A. Cipriani. *Heart Rhythm*. [Link](https://doi.org/10.1016/j.hrthm.2024.01.056)

**Diagnostic and Prognostic Value of Stress Cardiovascular Magnetic Resonance Imaging in Patients With Known or Suspected Coronary Artery Disease: A Systematic Review and Meta-analysis** (2023). F. Ricci, M. Y. Khanji, G. Bisaccia, A. Cipriani, A. Di Cesare, L. Ceriello, C. Mantini, M. Zimarino, A. Fedorowski, S. Gallina, S. E. Petersen and C. Bucciarelli-Ducci. *JAMA Cardiology*. [Link](https://doi.org/10.1001/jamacardio.2023.1290)

**Prognostic Significance of Late Gadolinium Enhancement in Fabry Disease-A Systematic Review and Meta-Analysis** (2023). F. Ricci, G. Bisaccia, D. Mansour, L. V. Molinari, M. Di Mauro, G. Renda, M. Y. Khanji and S. Gallina. *The American Journal of Cardiology*. [Link](https://doi.org/10.1016/j.amjcard.2023.06.059)

**CMR Reclassifies the Majority of Patients with Suspected MINOCA and non MINOCA** (2023). K. Liang, G. Bisaccia, I. Leo, M. G. L. Williams, A. Dastidar, J. W. Strange, E. Sammut, T. W. Johnson and C. Bucciarelli-Ducci. *European Heart Journal - Cardiovascular Imaging*. [Link](https://doi.org/10.1093/ehjci/jead182)

**Cardiovascular magnetic resonance reference values of mitral and tricuspid annular dimensions: the UK Biobank cohort** (2021). F. Ricci, N. Aung, S. Gallina, F. Zemrak, K. Fung, G. Bisaccia, J. M. Paiva, M. Y. Khanji, C. Mantini and S. Palermi. *Journal of Cardiovascular Magnetic Resonance*. [Link](https://doi.org/10.1186/s12968-020-00688-y)

## Cardiology

**Cardiovascular Morbidity and Mortality Related to Non-alcoholic Fatty Liver Disease: A Systematic Review and Meta-analysis** (2023). G. Bisaccia, F. Ricci, M. Y. Khanji, A. Sorella, E. Melchiorre, G. Iannetti, K. Galanti, C. Mantini, A. D. Pizzi, C. Tana, G. Renda, A. Fedorowski, R. De Caterina and S. Gallina. *Current Problems in Cardiology*. [Link](https://doi.org/10.1016/j.cpcardiol.2023.101643)

## General medicine

**Guillain–Barré syndrome and COVID-19 vaccination: a systematic review and meta-analysis** (2024). S. Censi, G. Bisaccia, S. Gallina, V. Tomassini and A. Uncini. *Journal of Neurology*. [Link](https://doi.org/10.1007/s00415-024-12186-7)

**Guillain-Barre syndrome and SARS-CoV-2 infection: a systematic review and meta-analysis on a debated issue and evidence for the 'Italian factor'** (2023). S. Censi, G. Bisaccia, S. Gallina, V. Tomassini and A. Uncini. *European Journal of Neurology*. [Link](https://doi.org/10.1111/ene.16094)

# Reviews

## Cardiovascular imaging

**The Role of Multimodality Imaging in Pediatric Cardiomyopathies** (2023). S. Moscatelli, I. Leo, F. Bianco, N. Borrelli, M. Beltrami, M. Garofalo, E. G. Milano, G. Bisaccia, F. Iellamo, P. P. Bassareo, A. Pradhan, A. Cimini and M. A. Perrone. *Journal of Clinical Medicine*. [Link](https://doi.org/10.3390/jcm12144866)

**The Role of Advanced Cardiovascular Imaging Modalities in Cardio-Oncology: From Early Detection to Unravelling Mechanisms of Cardiotoxicity** (2023). I. Leo, M. Vidula, G. Bisaccia, M. C. Procopio, R. Licordari, M. Perotto, G. La Vecchia, N. Miaris, P. E. Bravo and C. Bucciarelli-Ducci. *Journal of Clinical Medicine*. [Link](https://doi.org/10.3390/jcm12154945)

**Imaging patients with myocardial infarction with non-obstructive coronary arteries (MINOCA)** (2023). I. Leo, G. Bisaccia, N. Miaris, M. C. Procopio, R. Licordari and C. Bucciarelli-Ducci. *Heart*. [Link](https://doi.org/10.1136/heartjnl-2023-322835)

## Cardiovascular medicine

**Prognostic Value of High-Sensitivity Cardiac Troponin in Women** (2022). G. Bisaccia, F. Ricci, M. Y. Khanji, G. Gaggi, A. Di Credico, S. Gallina, A. Di Baldassarre and B. Ghinassi. *Biomolecules*. [Link](https://doi.org/10.3390/biom12101496)

**Post-Acute Sequelae of COVID-19 and Cardiovascular Autonomic Dysfunction: What Do We Know?** (2021). G. Bisaccia, F. Ricci, V. Recce, A. Serio, G. Iannetti, A. A. Chahal, M. Stahlberg, M. Y. Khanji, A. Fedorowski and S. Gallina. *Journal of Cardiovascular Development and Disease*. [Link](https://doi.org/10.3390/jcdd8110156)

**Mitochondrial Dysfunction and Heart Disease: Critical Appraisal of an Overlooked Association** (2021). G. Bisaccia, F. Ricci, S. Gallina, A. Di Baldassarre and B. Ghinassi. *International Journal of Molecular Sciences*. [Link](https://doi.org/10.3390/ijms22020614)

**Nonalcoholic fatty liver disease and cardiovascular disease phenotypes** (2020). G. Bisaccia, F. Ricci, C. Mantini, C. Tana, G. L. Romani, C. Schiavone and S. Gallina. *SAGE Open Medicine*. [Link](https://doi.org/10.1177/2050312120933804)