---
#title: Giandomenico Bisaccia
format:
  html: default
  quarto-cv-pdf:
    hyperrefoptions: draft
author: Giandomenico Bisaccia, MD, PhD
date: last-modified
#jobtitle: Early career medical researcher
email: bisacciagiandomenico@gmail.com
phone: '+39 350 533 1123'
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
orcid: 0000-0003-4606-3093 # orcid identifier
linkedin: bisacciamd
#twitter: twitter # twitter handle
web: 'bisacciamd.github.io'
fontawesome: yes
nocite: '@*'
validate-yaml: false
csl: apa-cv.csl
---

::: {.content-visible when-profile="english"}
# Experience
*Harefield Hospital, London, UK* \hfill Sept 2022—Feb 2024

- Clinical research fellowship in CMR
  - Prepared the initial report for 250+ clinical CMR scans
  - Studied the clinical value of cardiovascular magnetic resonance in patients with chest pain, cardiomyopathies, and long term after cardiac transplantation
  - Improved research productivity among peers in various research groups
:::

::: {.content-visible when-profile="italian"}
# Esperienza
*Harefield Hospital, Londra, Regno Unito* \hfill Settembre 2022—Febbraio 2024

- Clinical research fellowship in risonanza magnetica cardiaca
  - Preparazione di 250+ report preliminari di studi clinici di risonanza magnetica cardiaca
  - Attività di ricerca sul valore clinico della risonanza magnetica cardiaca in pazienti con dolore toracico, cardiomiopatie, e a lungo termine dopo trapianto cardiaco

:::

::: {.content-visible when-profile="english"}

# Education

*London School of Economics, London, UK* \hfill Dec 2023—Dec 2025

- MSc in Health Economics, Outcomes and Management in Clinical Sciences (class of 2025)
  - Modules included Economic Analysis for Health Policy (distinction), Quality and Outcomes in Clinical Sciences (distinction)
  - Volunteered as the class Clinical Student Representative for 2023/24

*Royal Brompton Hospital, London, UK*  \hfill Oct—Dec 2022

- Clinical CMR training course
  - Underwent full-time training in cardiac MR under CMR Level 3 certified experts
  - Contributed to the CMR service of the hospital

*G. d’Annunzio University of Chieti and Pescara, Chieti, Italy*

- PhD in Neuroscience and Imaging (MED/11, Doctor Europaeus) \hfill Oct 2021—Mar 2024

   Thesis title: *Value of Quantitative Stress Perfusion CMR in the Long-Term Assessment of Cardiac Transplantation Recipients*
   
   Supervisors: Prof. Sabina Gallina, Prof. Chiara Bucciarelli-Ducci, and Prof. Fabrizio Ricci

   - Established an international collaboration between the University of Chieti, Italy and Harefield Hospital, London, UK 
   - Co-authored 17 peer-reviewed publications
   - Co-supervised 12 undergraduate and 4 postgraduate students
   - Presented research findings for 7 original research studies at major international conferences for cardiology (ESC, AHA) and cardiovascular imaging (EACVI, SCMR)
   - Was a finalist in the CMR 2024 Early Career Award, clinical track (2024)

- Master's Degree in Medicine (summa cum laude, equivalent to MD) \hfill Oct 2014—Apr 2021
  
  Thesis title: *CMR Reference Values of Mitral and Tricuspid Annular Dimensions: the UK BioBank Cohort* 
  
  Supervisors: Prof. Sabina Gallina, Prof. Fabrizio Ricci
  
  - Completed the «Path of Excellence» on electrophysiology between 2016 and 2019, with focus on surface electromyography (Supervisor: Prof. Gian Luca Romani)
    - First student to be enrolled in the local MD-PhD track
:::

::: {.content-visible when-profile="italian"}

# Istruzione

*London School of Economics, Londra, Regno Unito* \hfill Dicembre 2023—Dicembre 2025

- MSc in Health Economics, Outcomes and Management in Clinical Sciences (classe del 2025)
  - I corsi frequentati includono Economic Analysis for Health Policy (voto finale: distinction), Quality and Outcomes in Clinical Sciences (voto finale: distinction)
  - Rappresentante di classe volontario per l'anno accademico 2023/24

*Royal Brompton Hospital, Londra, Regno Unito*  \hfill Ottobre—Dicembre 2022

- Corso trimestrale di risonanza magnetica cardiaca
  - Training a tempo pieno in risonanza magnetica cardiaca sotto la supervisione di esperti CMR di livello 3
  - Contributo all'attività di refertazione dell'ospedale

*Università G. d'Annunzio di Chieti e Pescara, Chieti, Italia*

- Dottorato in Neuroscienze e Imaging (Doctor Europaeus) \hfill Ottobre 2021—Marzo 2024

   Tesi: *Value of Quantitative Stress Perfusion CMR in the Long-Term Assessment of Cardiac Transplantation Recipients*

   SSD: MED/11

   Supervisori: Prof.ssa Sabina Gallina, Prof.ssa Chiara Bucciarelli-Ducci, e Prof. Fabrizio Ricci

   - Autore o coautore di 17 pubblicazioni peer-reviewed
   - Correlatore di 12 laureandi and 4 specializzandi
   
- Laurea magistrale in Medicina e Chirurgia (LM-41, 110 e lode) \hfill Ottobre 2014—Aprile 2021
  
  Tesi: *CMR Reference Values of Mitral and Tricuspid Annular Dimensions: the UK BioBank Cohort* 

  SSD: MED/11

  Supervisori: Prof.ssa Sabina Gallina, Prof. Fabrizio Ricci
  
  - Percorso di Eccellenza in segnali elettrofisiologici nel triennio 2016-2019, con focus su elettromiografia di superficie (Supervisore: Prof. Gian Luca Romani)
    - Primo studente del Percorso ad essere selezionato per la track MD-PhD

:::

::: {.content-visible when-profile="english"}
# Teaching

*University of Padua, Italy* \hfill Jan 2024

- Lecture on CMR safety, MSc in Cardiac magnetic resonance imaging
:::

::: {.content-visible when-profile="italian"}
# Attività di insegnamento

*Università di Padova, Italia* \hfill Gennaio 2024

- Lezione a tema "Sicurezza in ambiente di risonanza magnetica", Master in Risonanza Magnetica Cardiaca
:::

::: {.content-visible when-profile="english"}
# Professional licenses

Good Clinical Practice certification. *National Institute for Health and Care Research*, London, UK \hfill Oct 2022

Basic Life Support Provider, American Heart Association. *“Dinamica” Training Center*, Rome, Italy \hfill Jun 2021

- Medical licenses 
  - UK: General Medical Council, reference number 8023039 \hfill Feb 2023
  - Italy: "Ordine dei Medici-Chirurghi ed Odontoiatri", Chieti, reference number 5690 \hfill May 2021

:::

::: {.content-visible when-profile="italian"}
# Licenze professionali

Good Clinical Practice certification. *National Institute for Health and Care Research*, Londra, Regno Unito \hfill Ottobre 2022

Basic Life Support Provider, American Heart Association. *“Dinamica” Training Center*, Roma, Italia \hfill Giugno 2021

- Abilitazione alla professione di medico-chirurgo
  - Regno Unito: General Medical Council, numero di iscrizione 8023039 \hfill Febbraio 2023
  - Italia: Ordine dei Medici-Chirurghi ed Odontoiatri di Chieti, numero di iscrizione 5690 \hfill Maggio 2021

:::

::: {.content-visible when-profile="english"}
# Professional skills

- Clinical research
  - systematic review and meta-analysis (5 published)
  - diagnostic studies (accuracy, clinical utility)
  - prognostic studies (data scraping, survival analysis)

- Data science 
  - Strong data modelling skills, R
  - Data visualizations
  - Dynamic, reproducible reporting in Quarto
  - Development and deployment of server-based Shiny applications

- IT
  - Proficient in Word, Excel, Powerpoint
  - Creation and maintainance of REDCap projects and Git repositories
  - Basic Adobe Illustrator
  - Prior experience in MATLAB
  - Basic LaTeX
:::

::: {.content-visible when-profile="italian"}
# Competenze professionali

- Ricerca clinica
  - revisione sistematica e meta-analisi (5 pubblicate)
  - studi diagnostici (accuratezza, utilità clinica)
  - studi prognostici (data scraping, analisi di sopravvivenza)

- Data science 
  - Competenze avanzate di data modelling in R
  - Visualizzazione dati in ggplot2
  - Reporting dinamico, riproducibile in Quarto
  - Sviluppo di applicazioni server-based in Shiny

- Competenze informatiche
  - Utente esperto di Word, Excel, Powerpoint
  - Creazione e manutenzione di progetti REDCap e repository Git
  - Adobe Illustrator base
  - Esperienza pregressa di MATLAB
  - LaTeX base
:::

::: {.content-visible when-profile="english"}
# Language certifications

- International English Language Testing System (IELTS) \hfill Nov 2023
  - Academic english. Listening 9.0; Reading 9.0; Speaking 8.5; Writing 7.5 (scored 1 to 10)

- Occupational English Test (OET) \hfill Feb 2023
  - Medical english. Listening A; Reading A; Speaking B; Writing B (scored E to A) 
:::

::: {.content-visible when-profile="italian"}
# Certificazioni di lingua

- International English Language Testing System (IELTS) \hfill Novembre 2023
  - Inglese accademico. Listening 9.0; Reading 9.0; Speaking 8.5; Writing 7.5 (scored 1 to 10)

- Occupational English Test (OET) \hfill Febbraio 2023
  - Inglese medico. Listening A; Reading A; Speaking B; Writing B (scored E to A) 
:::

::: {.content-visible when-profile="english"}
# Professional affiliations

- Membership to scientific societies
  - American Heart Association \hfill 2023—present
  - American College of Cardiology \hfill 2022—present
  - Society for Cardiovascular Magnetic Resonance \hfill 2022—present
  - European Society of Cardiology \hfill 2021—present
  - European Association of Cardiovascular Imaging \hfill 2021—present
  - Italian Society of Cardiology \hfill 2021—present

- Participation to working groups
  - SCMR Early career \hfill 2022—present
  - ACC Fellow in training \hfill 2022—present
  - Italian Society of Cardiology
    - Cardiovascular magnetic resonance imaging applications
    - Sex differences in cardiovascular disease
:::

::: {.content-visible when-profile="italian"}
# Affiliazioni

- Affiliazione a società scientifiche
  - American Heart Association \hfill 2023—presente
  - American College of Cardiology \hfill 2022—presente
  - Society for Cardiovascular Magnetic Resonance \hfill 2022—presente
  - European Society of Cardiology \hfill 2021—presente
  - European Association of Cardiovascular Imaging \hfill 2021—presente
  - Società Italiana di Cardiologia \hfill 2021—presente

- Partecipazione a working group
  - SCMR Early career \hfill 2022—presente
  - ACC Fellow in training \hfill 2022—presente
  - Società Italiana di Cardiologia
    - Applicazioni della RM
    - Differenze di genere
:::

::: {.content-visible when-profile="english"}
# Grants, prizes and awards

- Finalist, Early career award (clinical track), CMR 2024, London, UK \hfill Jan 2024
- Early Career Investigator Travel Grant, AHA Scientific Sessions, Philadelphia, USA \hfill November 2023
- Educational Grant, EACVI Conference, Barcelona, Spain \hfill May 2023
- Travel Grant, SCMR Conference, San Diego, USA \hfill Jan 2023
:::

::: {.content-visible when-profile="italian"}
# Grants, premi e riconoscimenti

- Finalista, Early career award (clinical track), CMR 2024, Londra, Regno Unito \hfill Gennaio 2024
- Early Career Investigator Travel Grant, AHA Scientific Sessions, Philadelphia, USA \hfill Novembre 2023
- Educational Grant, EACVI Conference, Barcelona, Spain \hfill Maggio 2023
- Travel Grant, SCMR Conference, San Diego, USA \hfill Gennaio 2023
:::

::: {.content-visible when-profile="english"}
# Publications
:::

::: {.content-visible when-profile="italian"}
# Pubblicazioni
:::

**Atrial electro-functional predictors of incident atrial fibrillation in cardiac amyloidosis** (2024).
G. Sinigiani, L. De Michieli, A. Porcari, C. Zocchi, A. Sorella, C. Mazzoni, G. Bisaccia, A. De Luca, G. Di Bella, D. Gregori, F. Perfetto, M. Merlo, G. Sinagra, S. Iliceto, M. Perazzolo Marra, D. Corrado, F. Ricci, F. Cappelli and A. Cipriani.
*Heart Rhythm*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1016/j.hrthm.2024.01.056)

**Underlying mechanisms and cardioprotective effects of SGLT2i and GLP-1Ra: insights from cardiovascular magnetic resonance** (2024).
A. Cersosimo, N. Salerno, J. Sabatino, A. Scatteia, G. Bisaccia, S. De Rosa, S. Dellegrottaglie, C. Bucciarelli-Ducci, D. Torella and I. Leo.
*Cardiovascular Diabetology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1186/s12933-024-02181-7)

**Guillain–Barré syndrome and COVID-19 vaccination: a systematic review and meta-analysis** (2024).
S. Censi, G. Bisaccia, S. Gallina, V. Tomassini and A. Uncini.
*Journal of Neurology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1007/s00415-024-12186-7)

**Diagnostic and Prognostic Value of Stress Cardiovascular Magnetic Resonance Imaging in Patients With Known or Suspected Coronary Artery Disease: A Systematic Review and Meta-analysis** (2023).
F. Ricci, M. Y. Khanji, G. Bisaccia, A. Cipriani, A. Di Cesare, L. Ceriello, C. Mantini, M. Zimarino, A. Fedorowski, S. Gallina, S. E. Petersen and C. Bucciarelli-Ducci.
*JAMA Cardiology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1001/jamacardio.2023.1290)

**Prognostic Significance of Late Gadolinium Enhancement in Fabry Disease-A Systematic Review and Meta-Analysis** (2023).
F. Ricci, G. Bisaccia, D. Mansour, L. V. Molinari, M. Di Mauro, G. Renda, M. Y. Khanji and S. Gallina.
*The American Journal of Cardiology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1016/j.amjcard.2023.06.059)

**The Role of Multimodality Imaging in Pediatric Cardiomyopathies** (2023).
S. Moscatelli, I. Leo, F. Bianco, N. Borrelli, M. Beltrami, M. Garofalo, E. G. Milano, G. Bisaccia, F. Iellamo, P. P. Bassareo, A. Pradhan, A. Cimini and M. A. Perrone.
*Journal of Clinical Medicine*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/jcm12144866)

**CMR Reclassifies the Majority of Patients with Suspected MINOCA and non MINOCA** (2023).
K. Liang, G. Bisaccia, I. Leo, M. G. L. Williams, A. Dastidar, J. W. Strange, E. Sammut, T. W. Johnson and C. Bucciarelli-Ducci.
*European Heart Journal - Cardiovascular Imaging*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1093/ehjci/jead182)

**The Role of Advanced Cardiovascular Imaging Modalities in Cardio-Oncology: From Early Detection to Unravelling Mechanisms of Cardiotoxicity** (2023).
I. Leo, M. Vidula, G. Bisaccia, M. C. Procopio, R. Licordari, M. Perotto, G. La Vecchia, N. Miaris, P. E. Bravo and C. Bucciarelli-Ducci.
*Journal of Clinical Medicine*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/jcm12154945)

**Imaging patients with myocardial infarction with non-obstructive coronary arteries (MINOCA)** (2023).
I. Leo, G. Bisaccia, N. Miaris, M. C. Procopio, R. Licordari and C. Bucciarelli-Ducci.
*Heart*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1136/heartjnl-2023-322835)

**Guillain-Barre syndrome and SARS-CoV-2 infection: a systematic review and meta-analysis on a debated issue and evidence for the 'Italian factor'** (2023).
S. Censi, G. Bisaccia, S. Gallina, V. Tomassini and A. Uncini.
*European Journal of Neurology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1111/ene.16094)

**Cardiovascular Morbidity and Mortality Related to Non-alcoholic Fatty Liver Disease: A Systematic Review and Meta-analysis** (2023).
G. Bisaccia, F. Ricci, M. Y. Khanji, A. Sorella, E. Melchiorre, G. Iannetti, K. Galanti, C. Mantini, A. D. Pizzi, C. Tana, G. Renda, A. Fedorowski, R. De Caterina and S. Gallina.
*Current Problems in Cardiology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1016/j.cpcardiol.2023.101643)

**Prognostic Value of High-Sensitivity Cardiac Troponin in Women** (2022).
G. Bisaccia, F. Ricci, M. Y. Khanji, G. Gaggi, A. Di Credico, S. Gallina, A. Di Baldassarre and B. Ghinassi.
*Biomolecules*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/biom12101496)

**Cardiovascular magnetic resonance reference values of mitral and tricuspid annular dimensions: the UK Biobank cohort** (2021).
F. Ricci, N. Aung, S. Gallina, F. Zemrak, K. Fung, G. Bisaccia, J. M. Paiva, M. Y. Khanji, C. Mantini and S. Palermi.
*Journal of Cardiovascular Magnetic Resonance*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1186/s12968-020-00688-y)

**Post-Acute Sequelae of COVID-19 and Cardiovascular Autonomic Dysfunction: What Do We Know?** (2021).
G. Bisaccia, F. Ricci, V. Recce, A. Serio, G. Iannetti, A. A. Chahal, M. Stahlberg, M. Y. Khanji, A. Fedorowski and S. Gallina.
*Journal of Cardiovascular Development and Disease*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/jcdd8110156)

**Mitochondrial Dysfunction and Heart Disease: Critical Appraisal of an Overlooked Association** (2021).
G. Bisaccia, F. Ricci, S. Gallina, A. Di Baldassarre and B. Ghinassi.
*International Journal of Molecular Sciences*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/ijms22020614)

**Nonalcoholic fatty liver disease and cardiovascular disease phenotypes** (2020).
G. Bisaccia, F. Ricci, C. Mantini, C. Tana, G. L. Romani, C. Schiavone and S. Gallina.
*SAGE Open Medicine*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1177/2050312120933804)

::: {.content-visible when-profile="english"}
# Main presentations at conferences
:::

::: {.content-visible when-profile="italian"}
# Presentazioni orali a congressi internazionali
:::

**Prognostic Value of Myocardial Blood Flow Index Among Heart Transplant Recipients**
G. Bisaccia, R. Licordari, I. Leo, G. La Vecchia, M. Perotto, M. C. Procopio, F. Ricci, S. Gallina, J. Wong and C. Bucciarelli-Ducci. [Presented at CMR 2024 (Jan 2024).]{.content-visible when-profile="english"} [Presentata a CMR 2024 (Gennaio 2024).]{.content-visible when-profile="italian"}

**Safety and Feasibility of Adenosine Stress CMR for CAV Detection in Orthotopic Heart Transplant Recipients**
G. Bisaccia, R. Licordari, I. Leo, G. La Vecchia, M. Perotto, M. C. Procopio, F. Ricci, S. Gallina, J. Wong and C. Bucciarelli-Ducci. [Presented at CMR 2024 (Jan 2024).]{.content-visible when-profile="english"} [Presentata a CMR 2024 (Gennaio 2024).]{.content-visible when-profile="italian"}

**Comparative and Incremental Diagnostic and Prognostic Yield of Exercise ECG, CMR and SPECT in Patients With Suspected Ischaemic Heart Disease: A CE-MARC Sub-Study**
G. Bisaccia, P. P. Swoboda, C. Bucciarelli-Ducci, S. Plein and J. Greenwood. [Presented at AHA Scientific Sessions, Philadelphia, USA (Nov 2023)]{.content-visible when-profile="english"} [Presentata a AHA Scientific Sessions, Philadelphia, USA (Novembre 2023)]{.content-visible when-profile="italian"}

**CMR reclassifies patients with suspected myocardial infarction with non-obstructive coronary arteries (MINOCA)**
G. Bisaccia, K. Liang, M. G. L. Williams, I. Leo, A. Dastidar, E. Sammut, T. Johnson and C. Bucciarelli-Ducci. [Presented at EACVI, Barcelona, Spain (May 2023)]{.content-visible when-profile="english"} [Presentata a EACVI, Barcellona, Spagna (Maggio 2023)]{.content-visible when-profile="italian"}

**Prognostic yield of stress CMR to evaluate chronic coronary syndromes: a systematic review and meta-analysis**
G. Bisaccia, M. Khanji, S. Gallina, S. Petersen, C. Bucciarelli-Ducci and F. Ricci. [Presented at ESC Congress, Barcelona, Spain (August 2022)]{.content-visible when-profile="english"} [Presentata a ESC Congress, Barcellona, Spagna (Agosto 2022)]{.content-visible when-profile="italian"}

**Diagnostic accuracy of stress CMR to evaluate chronic coronary syndromes: an updated meta-analysis**
G. Bisaccia, M. Khanji, S. Gallina, S. Petersen, C. Bucciarelli-Ducci and F. Ricci. [Presented at ESC Congress, Barcelona, Spain (August 2022)]{.content-visible when-profile="english"} [Presentata a ESC Congress, Barcellona, Spagna (Agosto 2022)]{.content-visible when-profile="italian"}

**Cardiovascular morbidity and mortality related to non-alcoholic fatty liver disease: a systematic review and meta-analysis of prospective studies**
G. Bisaccia, F. Ricci, E. Melchiorre, C. Tana, G. Renda, M. Khanji, A. Fedorowski, R. De Caterina and S. Gallina. [Presented at ESC Congress (The Digital Experience) (August 2021)]{.content-visible when-profile="english"} [Presentata a ESC Congress (The Digital Experience) (Agosto 2021)]{.content-visible when-profile="italian"}

::: {.content-visible when-profile="english"}
# References
Available upon request.
:::

::: {.content-visible when-profile="italian"}
# Lettere di referenza
Fornite su richiesta.
:::